---

name: unit-tests

# Controls when the workflow will run
on:  # yamllint disable-line rule:truthy
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Cache APT Packages
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: cmake

      - name: Compile taskwarrior
        run: |
          cd /tmp
          git clone https://github.com/GothenburgBitFactory/taskwarrior
          cd taskwarrior
          cmake -DCMAKE_BUILD_TYPE=release -DENABLE_SYNC=OFF .
          make
          sudo make install

      - name: Print taskwarrior version
        run: task --version

      - name: Install python dependencies
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: coverage run --source=src -m pytest

      - name: Generate report
        run: coverage xml

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: b62ba758-60a5-4c16-9cd9-f9fd7fc3560e
          fail_ci_if_error: true
